### ISSUE TITLE
No Audio using HMDI

### ISSUE THREAD

**Issue by mahlovic** [m64p/m64p#127]
Maybe I missed something crucial. I tried everything but can't seem to get the sound working using HMDI.

**Comment by loganmc10** [comment]
Does it work when you don't use HDMI? What OS are you using?

**Comment by mahlovic** [comment]
yes I tested it on my laptop and there it works fine. I tried to find output configs to force the audio go through HDMI. Both systems I use are Windows 10.

**Comment by Defreezer** [comment]
I'm running it on Windows 7 x64 and I can confirm it gives absolutely no audio, even after disabling HDMI audio output (on a monitor that doesn't have speakers) and having all audio played through a 3.5mm jack. The GUI could use some more audio options.

**Comment by loganmc10** [comment]
Windows 7 is not supported, no audio there is a known issue (won't be fixed)

**Comment by Jj0YzL5nvJ** [comment]
**WASAPI** mpv-player/mpv#4361

> It's easier to see the problem when you have headphones connected to the front and speakers on the back connection. When you disconnect the headphones, BOOM!
