### ISSUE TITLE
Controller does not work in game, but I am able to create profiles.

### ISSUE THREAD

**Issue by Edacaf** [m64p/m64p#142]
I am using a 3rd party Wii U GameCube adapter. This device successfully works on Project64, Dolphin, and other emulators. Unfortunately the exact model is no longer available on Amazon for more details. 

When creating a controller profile in m64p there is no problem, however when I start a game none of my inputs work.

The [issue posted here ](https://github.com/loganmc10/m64p/issues/12#issuecomment-642882911)sounds exactly my problem. Later in the thread they state it was simply fixed without any further intervention. I am unfortunately not able to get it to work just yet.

"I believe I am having the same issue.
I'm using the latest files (M64P June62020-4d7af20) on Windows 10, with an old Mayflash 
Dual N64 to USB adapter.
It shows up as '0:HuiJia SNES Controller' and '1:HuiJia SNES Controller' in the config, so I wonder if it shares VID/PID.
Funny thing is, the Profile Editor detects the controller fine, and I can set all the buttons, but no inputs work ingame! I've tried 0 and 1 in case I'd plugged my pad into the wrong slot, but no dice."

_Originally posted by @Jaffacakelover in https://github.com/loganmc10/m64p/issues/12#issuecomment-642882911_

**Comment by loganmc10** [comment]
Can you please download the latest version here? https://github.com/loganmc10/m64p/releases The June62020 build is quite old

**Comment by Edacaf** [comment]
I am currently on the February 23, 2021 build.

Attached are some screenshots for assistance. I have captured my current controller settings where m64p recognized my inputs during the profile creation process, as well as the gamepad list. I have tried on each Gamepad option listed but none work. 

![Capture](https://user-images.githubusercontent.com/81643042/113030622-ce0de280-915b-11eb-959f-be5878ebac9e.PNG)
![Untitled](https://user-images.githubusercontent.com/81643042/113030833-02819e80-915c-11eb-81ee-36dd4aab8511.png)

**Comment by PRGilland** [comment]
I have this same exact problem. I can put the inputs on the profile, but it doesn't work in-game.

This is the 3rd-party gamecube controller adapter I am using:
https://www.amazon.com/gp/product/B07Q459FBQ

I wonder if you have the same one.

I'm using the June 23, 2021 build.

**Comment by Collectathon** [comment]
I also have this issue with an N64 mayflash adapter

**Comment by DarthSidious666** [comment]
Is this still happening with the latest build?

**Comment by Collectathon** [comment]
> Is this still happening with the latest build?

I can confirm that it is not happening anymore for me in the latest build. m64p now successfully detects inputs while emulating a rom.
