### ISSUE TITLE
Discord streaming crashes the emulator and as I'm aware it's only Windows 10 but it might do it for other operating systems.

### ISSUE THREAD

**Issue by AkihitoZero5454** [m64p/m64p#172]
Whenever I try to use Discord streaming it crashes and closes the emulator. Is it because Discord streaming support wasn't implemented yet or is it a bug?

**Comment by loganmc10** [comment]
I'm not too familiar with all of Discord's features. When you say Discord streaming, do you mean sharing your screen in a voice chat channel, or is this some other feature?

**Comment by AkihitoZero5454** [comment]
> I'm not too familiar with all of Discord's features. When you say Discord streaming, do you mean sharing your screen in a voice chat channel, or is this some other feature?

Yes, sharing your screen that's the one!

**Comment by loganmc10** [comment]
I couldn't reproduce this, I was able to screen/application share, although doing an application share does distort the image. I'm afraid there probably isn't much I can do about any of this, there is really no documentation from Discord on what to do to improve screen sharing for an application
