### ISSUE TITLE
DK64 runs too well

### ISSUE THREAD

**Issue by CLGZFGFrankerZ123** [m64p/m64p#173]
The game relies on the game lagging for a handful of things to function properly, and this doesn't lag enough. For example, on the DKTV screen (the "Press Start" screen), DK's and Chunky's sections notably desync. After DK climbs up a cliff, he's supposed to shoot a switch; instead he falls down in the water. Chunky is supposed to shoot and kill a Kasplat, but all of his shots miss.

**Comment by chronological-git** [comment]
I think Goldeneye 007 has a similar issue to this because I noticed that during the gun barrel opening Bond walks to the center of the screen too quickly.

**Comment by Tasosgemah** [comment]
Goldeneye runs too fast in the attract/demo mode as well. The same applies with EWJ 3D, the demo is like running in fast forward. Knife edge runs too fast ingame.

These issues plague all N64 emulators since the beginning.

**Comment by blikblum** [comment]
Should be fixed by this [release](https://github.com/m64p/m64p/releases/tag/v2022.07.7)?

**Comment by loganmc10** [comment]
yes fixed now!
