### ISSUE TITLE
Framerate randomly dips in San Francisco Rush

### ISSUE THREAD

**Issue by Kombatologist** [m64p/m64p#187]
**Describe the bug**
Getting random framerate dips after issue #186 was resolved. Not entirely sure if it's my system specs or m64p, but I wasn't experiencing this issue before. For comparison's sake, I tested Rush 2 on the same build and it runs fine.

**To Reproduce**
Tested on track 2 (but should occur randomly on any track) using m64p's default settings.

**Expected behavior**
While the game does suffer from occasional slowdown on real hardware, it's not this severe.

**Screenshots**
I uploaded a video demonstrating the issue here (see the 00:00:15 and 00:00:35 mark): https://youtu.be/BMlc4mtXwZ4

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - CPU: Ryzen 7 3800X
 - GPU: RX 590

**Additional context**
None.

**Comment by Jj0YzL5nvJ** [comment]
[`GL_CLIENT_STORAGE_BIT`?](https://github.com/gonetz/GLideN64/pull/1960)

**Comment by loganmc10** [comment]
> I wasn't experiencing this issue before

Do you mean you weren't experiencing slowdowns before when it was GlideN64, or before when it was flickering with Parallel RDP?

**Comment by Kombatologist** [comment]
> Do you mean you weren't experiencing slowdowns before when it was GlideN64, or before when it was flickering with Parallel RDP?

When it was flickering with Parallel RDP.

**Comment by Kombatologist** [comment]
> 
> 
> Can you try the latest version? There have been some updates to the graphics plugin

Seems a little better. But now it appears to happen in specific spots 100% of the time. I'll have to dig out my N64 and test it to see if those specific dips in frame rate occur on real hardware. (Though I used to play the game religiously and I don't recall it being like that.)
