### ISSUE TITLE
Settings do not scale

### ISSUE THREAD

**Issue by tony971** [m64p/m64p#193]
**Describe the bug**
The settings menu does not scale with Windows scaling

**To Reproduce**
1. Customize the scale and layout in the Display settings of Windows
2. Open the m64p settings window
3. Realize that the text and options have not scaled

**Expected behavior**
Settings scale with Windows

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/7101253/123693444-e9e15d00-d80c-11eb-9c07-04fbbdcbc5a4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Nvidia GeForce 1080

**Comment by ForeskinJohn** [comment]
thank god, ive had this issue to, but the only way to fix it is to overwrite your m64p files with a fresh install, i dont think anyone is looking into this issue

**Comment by DarthSidious666** [comment]
Does this still happen?

**Comment by DarthSidious666** [comment]
Scaling issue solved, just checked in WIndows.
