### ISSUE TITLE
Weird Text Not Clearing in Mortal Kombat Trilogy

### ISSUE THREAD

**Issue by crhy** [m64p/m64p#203]
**Describe the bug**
You can see some of the sprites stay online after they should have cleared.

**To Reproduce**
1. Start a game.
2. Play for a while.
3. See the weird left over text on the screen.

**Expected behavior**
This is a sprite that's supposed to go away after a brief animation.

**Screenshots**
![mp64error](https://user-images.githubusercontent.com/21183395/126866853-156d7b0b-8fbe-4d54-9e0f-d69e980927b7.png)

**Desktop (please complete the following information):**
 - Mint 20.1
 - Latest Build
 - GPU: Nvidia GTX 760

**Additional context**

**Comment by Meerkov** [comment]
This is a pretty bad bug report.

There is a lot of text on that screen. Which text are you referring to? I don't see anything unusual here.

**Comment by thekovic** [comment]
How about the cut-off text sprites at the bottom of the screen? Those look pretty sus to me
