### ISSUE TITLE
Hardcoded shortcuts overriding certain keys

### ISSUE THREAD

**Issue by KnotUntied** [m64p/m64p#205]
**Describe the bug**
Mapping keys such as `M` (the mute shortcut) result in the program using the shortcut without registering the input within the game, rendering such keys unusable in the configuration (e.g. with `M` mapped to the B button, pressing `M` mutes the game but does not register the B button).

**To Reproduce**
1. Go to Settings > Controller Configuration
2. Under Manage Profiles, Edit Profile
3. Assign `M` to a button or stick.
4. Run a game

**Expected behavior**
Expected keys such as `M` to perform their assigned inputs in the configuration (e.g. the B button, see screenshot).

**Screenshots**
<img width="449" alt="Screenshot 2021-07-29 175232" src="https://user-images.githubusercontent.com/20182921/127471991-10ef5149-399c-4543-a0c7-1aee875c5ada.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 20H2
 - GPU: AMD Radeon(TM) Vega 8 Graphics

**Additional context**
The number row (such as `1` being assigned to the Start button) may not work as well for the same reason.

**Comment by KnotUntied** [comment]
Editing the configuration file (i.e. `mupen64plus.cfg` in, `%APPDATA%\Mupen64Plus` as documented [here](https://mupen64plus.org/wiki/index.php?title=KeyboardSetup#3._Configuration_for_Key_Commands)) remedies this, but requires fiddling outside the GUI.

**Comment by DarthSidious666** [comment]
Since this can be worked around there's not really much to do for this.
Hard-coded keys are needed for certain functionality.
