### ISSUE TITLE
Screen tears how to fix ?

### ISSUE THREAD

**Issue by 3dfxguy** [m64p/m64p#215]
I just discover this awesome emulator and it's running great but I am having screen tears what are option to set vsync  I am running the m64p .
my system 👍 

Windows 10 LTSC
AMD Ryzen 1700
16g DDR4 3200
Nvidia GTX 1060 3gb

Thanks in Advance.

**Comment by 3dfxguy** [comment]
I have a quick fix for the screen tear  run RTSS and set the scanline sync to -200 and tears are gone. 


 
![1](https://user-images.githubusercontent.com/91288527/134794959-167fcfe6-3d4f-4a17-80e7-8bbd75b4568c.JPG)

**Comment by Immersion95** [comment]
Rtss is great but it prevents fast-forward. It would be great to have a Vsync implementation.

**Comment by loganmc10** [comment]
Vsync would also prevent fast forward

**Comment by Immersion95** [comment]
> Vsync would also prevent fast forward

Would it be possible to disable it while fast-forwarding ? If it isn't, thanks anyway.

**Comment by loganmc10** [comment]
Yes that should be possible. Right now the rendering system is a little hacky. Vulkan is used for 99% of the work but the final image is rendered in OpenGL.

In hoping to rework it soon so it's all Vulkan, then I'll worry about proper vsync support

**Comment by Immersion95** [comment]
> Yes that should be possible. Right now the rendering system is a little hacky. Vulkan is used for 99% of the work but the final image is rendered in OpenGL.
> 
> In hoping to rework it soon so it's all Vulkan, then I'll worry about proper vsync support

It now works flawlessly, thx a lot !

The only missing feature is frame skipping while fast forwarding as Vsync prevents it from working.

This issue should be closed though.

**Comment by loganmc10** [comment]
> The only missing feature is frame skipping while fast forwarding as Vsync prevents it from working.

You can't really skip frames without potentially messing up emulation. Some games read back the frame buffer (Pokemon Snap for instance actually "looks at" the framebuffer to determine what pictures you took). However, there is probably a way to just temporarily disable vsync while a user is fast forwarding, I'll have to think about it
