### ISSUE TITLE
ParaLLEl version audio crackle/gameplay stutter

### ISSUE THREAD

**Issue by Xiathan** [m64p/m64p#223]
Describe the bug
Using the Nov 4 build of the ParaLLEl version, lots of music has a subtle crackling in several games.

To Reproduce

Play the games and compare to the Glide/AngryLion version. Games I tested were Mario 64, Mario Golf, and Paper Mario. Moreover, the fix that some have suggested in previous instances of audio issues by using an older plugin seems to be broken with the newest build.

Desktop (please complete the following information):

OS: Windows
Version: 10
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
GPU: GTX 1050Ti

**Comment by Xiathan** [comment]
To give a quick update, after the Feb 3 release, the issue is mostly fixed in Mario Golf, but remains in Paper Mario. Particularly, the low bass notes on the file select screen are where the crackling is most noticeable. And to clarify, I am comparing to the Angrylion LLE mode of the Glide/AL version, not using Glide. Also, this crackling isn't the kind of stuttering that comes from a game slowdown, the games are running at full speed with both AL and ParaLLEl

**Comment by chiefisreal** [comment]
OOT has this issue, Audio in PJ64 isn't all that great but unfortunately its better then m64p atm with AziAudio v0.70 WIP10 audio plugin. GlideN64 had a shader cache Dose ParaLLEl have one also? I've seen no evidence of it like I do with GlideN64. I hear that Audio crackles are causes by shaders generating and with no cache it will happen more often.

**Comment by loganmc10** [comment]
I've made a few changes that will hopefully help some with performance. Please retest with the latest version and reopen if the issue persists

**Comment by Xiathan** [comment]
I retested Paper Mario with build 3f1da83, the issue is improved but not fixed. The bass notes in the overture theme during the preview are clean, but the overture version with whistling on the file select screen still has crackly bass notes. Other games I tested were again Mario 64 and Mario Golf, they performed fine.
