### ISSUE TITLE
Config Dir Path change doesn't seem to affect where saves are stored

### ISSUE THREAD

**Issue by thekovic** [m64p/m64p#227]
**Describe the bug**
I have changed the plugin path to an absolute path (specifically in my case "D:/Hry/m64p-win64/mupen64plus") and moved all the contents of the previous folder used for configs (in my case "C:\Users\<Windows username>\AppData\Roaming\Mupen64Plus") into the new folder. The emulator correctly found and recognized my existing controller profiles but saves from the saves folder (like EEPROM info, controller pak saves and save states) were not found and were generated again at the old folder in AppData.

**To Reproduce**
1. Launch a game with EEPROM saves (like Ocarina of Time or Indiana Jones)
2. Change config dir path and move your .eep file in there
3. Launch the game again
4. Observe that your saved progress is not found and you start from scratch. New files were generated at the old location.

**Expected behavior**
Save files and generate/are recognized at the new location.

**Screenshots**
![image](https://user-images.githubusercontent.com/72971433/144635292-03037acb-26c5-44e7-9375-82c5d51e1a57.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 10
 - GPU: 1050Ti

EDIT: I have done some testing with the new build that released today and seems my initial observation was incorrect, mupen64plus.cfg is being located, stored and recognized correctly. Only the saves are still being stored and generated in AppData.

**Comment by loganmc10** [comment]
I can't reproduce this. I set my config path to a "hello" folder in my home directory, and it creates these files:

![image](https://user-images.githubusercontent.com/848146/144637325-327b2ad3-b01d-45af-ab53-b00bf328da57.png)

I verified that changing settings in the GUI updates that copy of mupen64plus.cfg

Save files aren't config, they are data, there isn't currently a way to override the data location

**Comment by thekovic** [comment]
See my edit above, I came to the same conclusion, apologies for my initial report being incorrect. As far as the save go, that's unintuitive shall we say. This the realm of feature request now, I guess, because it's technically doing what it's supposed to but is there any chance you could make it so the dialog affects saves as well? The reason why I wanted to edit this in the first place is so that I have all emulator files in the emulator folder and not have them dumped into Users on my boot drive.

**Comment by loganmc10** [comment]
I misspoke earlier, it is possible to change the save path, it's just not very intuitive, it's in the core configuration options:

![image](https://user-images.githubusercontent.com/848146/144638696-725f8f4e-faa0-48d5-bdf9-cde623a56d4b.png)

There is no file browser there, so you just need to paste in a proper path and restart the emulator

**Comment by thekovic** [comment]
Yes, that works. It is really not intuitive at all, not only are the options themselves quite hidden but also by default the value is as stated ${UserDataPath}/save, which I thought means the path + /save as an added suffix but the /save is part of the value so if you insert your custom value instead, you need to include /save yourself.

Removing these options from the Core menu and placing them along with the other path settings + making them more clear is something for the long list in the far future. For now, I think the issue is solved, in the end it was just a misunderstanding on my part because I expected it to work differently than it actually does.
