### ISSUE TITLE
 ParaLLEl-RDP changed, m64p still not capturing screenshots in native resolution

### ISSUE THREAD

**Issue by wildgoosespeeder** [m64p/m64p#228]
I couldn't find an open issue with this exact problem.

**Describe the bug**
#135 is related but not 100% due to some backends being changed. The idea is that the screenshot code seems to be using whatever resolution is of the emulator Window, minus Windows or QT GUI elements, instead of the internal resolution. This creates screenshots looking pixelated.

I am not asking to upscale N64 graphics before screenshots are taken in this case. I know how to adjust those kind of settings. I just prefer not to. I am strictly keeping it to what a real N64 would produce.

**To Reproduce**
1. As the game is running take a picture (F12). Do not upscale rendering resolution to make 3D models look smooth on high resolution displays.
2. Resize window to bigger or smaller, take another picture
3. Ideally take something that is smaller than 320x340 and bigger than 640x480 or 800x600 or other resolutions that are 4:3 ratio.
4. Screenshots are not sized to native resolution (or selected upscaled resolution) but are the size of the Window, minus Windows or QT GUI elements.

**Expected behavior**
Something similar to how Project64 handles screenshots.

**Screenshots**
m64p output
![paper_mario-003](https://user-images.githubusercontent.com/18543809/144658605-78a453e5-6f70-418b-9e75-51c10b6b3922.png)
![paper_mario-004](https://user-images.githubusercontent.com/18543809/144658607-bc93a15c-8ec2-44a6-8b23-ce027a604b77.png)
![paper_mario-005](https://user-images.githubusercontent.com/18543809/144658609-9e8e6876-d577-4167-9fe7-eca0ebe4fc15.png)

Project64 output (angrylion):
![NMQE0050](https://user-images.githubusercontent.com/18543809/144658788-e37f507a-13a4-46c6-9f3f-f4e91f110ca4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2
 - GPU: GeForce GTX 1660Ti
 - m64p version: Dec 3, 2021

**Additional context**
I believe the angrylion plug-in (and hopefully the new ParaLLEl-RDP) is very close to what a real N64 can produce. I just don't know why the screenshot code is stretching a 320x240 output to match what the Window is displaying. Maybe I am missing a setting. I also deal with this sort of problem with Dolphin emulator but I have found a convoluted work-around. Haven't checked lately if it is 100% fixed, but I digress.

I'm glad that crashing no longer happens as described in #134 and #111. Thank you @loganmc10! I hope I am making sense to you!

**Comment by loganmc10** [comment]
I'm going to close this, it's more of a feature request than a bug report.

Your issue is actually with upstream mupen64plus, the Mupen64Plus API defines the screenshot function as "This function reads the pixels of the frame buffer"[1]. The screenshot function is meant to capture what is on the screen. I'm open to a PR or something to make it behave differently, but as of now, I consider it working as expected.

[1]https://github.com/mupen64plus/mupen64plus-core/blob/master/doc/emuwiki-api-doc/Mupen64Plus-v2.0-Plugin-API.mediawiki#mupen64plus-v20-video-plugin-api

**Comment by wildgoosespeeder** [comment]
That's a shame because mupen64plus, from what I understand, is a fractal of forks; command lines and GUIs to make the experience more tolerable, like Linux for an operating system. Might be very hard to fix a simple issue by fixing a core mupen64plus library. I don't know how to present the issue since my experience is through the lens of m64p and not mupen64plus. Thought that maybe since the project is open source, the code could be examined to see where the fault lies and take matters into your own hands with your forked m64p. The only two pre-WiiU Nintendo emulators I have ever had this issue with is Dolphin and m64p.

Had some hope that maybe I can ditch Project64 for good and go with m64p as the go-to emulator for simplicity with everything. Despite Project64 having some glaring limitations of its plug-in structure and maybe an outdated coding model throughout the years, still present to this day, despite being on GitHub, the only plus it has is the screenshots it can take (N64 mouse support too for 64DD). That's the only reason I keep it.

I do use m64p for regular play. Project64 is too slow with LLE and may have glitches with faster HLE plug-ins. Most of the time, Project64 has 60 VI/s or whatever it is that matches a 480i TV's refresh rate (30FPS/60FPS) on my hardware, but it slows down more frequently compared to m64p when playing the same section of a game. No faulting that. Very good stuff. Only issue is the screenshot code. Hopefully this issue gets revisited and reconsidered.
