### ISSUE TITLE
[Feature Request] Implement Controller Profile Assignment 

### ISSUE THREAD

**Issue by CassiusOtho** [m64p/m64p#230]
**Describe the bug/ feature request**
It would be great if we could select controller profiles for each game so that the game automatically opens with the users selected profiles. It would save the end user some time, especially those of us that like to use custom profiles. Cemu has a really great way of doing this. I have attached some pictures that give a better idea of how the Wii U emulator uses this feature which could provide some inspiration. 

**To Reproduce / How it works**
For starters Cemu has a games list that is visible when the program is opened. This is a crucial first step to enable custom controller setup. By right clicking on the game and going to "Edit game profile" it takes you to an "Edit game profile" box. In the far right there is the "Controller" option. Clicking here allows selection of profiles for the various controllers. The game now opens with that controller profile. 

**Right clicking a game displays the image below:** / **Screenshots**
![Cemu Controller Config 1](https://user-images.githubusercontent.com/63135347/130235218-e2459245-81e3-440f-a703-d1a791872963.jpg)

**Clicking "Edit game profile" displays the image below:** / **Screenshots**
![Cemu Controller Config 2](https://user-images.githubusercontent.com/63135347/130235221-7a6e5237-7a40-400d-a02b-295962b00f26.jpg)

**Comment by loganmc10** [comment]
Just FYI I'm not actively working on feature requests, so this is probably going to sit here unaddressed unless someone else picks it up

**Comment by CassiusOtho** [comment]
No problem. Thank you for letting me know.
