### ISSUE TITLE
Major League Baseball Ken Griffey Jr. intro flickering

### ISSUE THREAD

**Issue by Meerkov** [m64p/m64p#235]
**Describe the bug**
The introscreen flickers when starting Major League Baseball Ken Griffey Jr.

**To Reproduce**
1. start Major League Baseball Ken Griffey Jr.
2. Notice flickering of the title cards

**Expected behavior**
No flickering.

**Screenshots**
![image](https://user-images.githubusercontent.com/8139496/151108153-533439ec-12cd-474f-8787-9ec4ea1a416e.png)

**Additional context**
I want to say that for some reason, this game doesn't emulate very well on nearly any other emulator. I'm not sure why. But m64p runs that game *almost* flawlessly.

**Comment by loganmc10** [comment]
Yes this is a common issue, also present in GLideN64 (https://github.com/gonetz/GLideN64/issues/1664). I assume the issue lies with the emulator core, since it is present across multiple video plugins

**Comment by Meerkov** [comment]
That's fair. I wanted to bring it up because the behavior is much *less* on this core than on GLideN64. But I'd certainly take the expert feedback that it may be CPU related.

**Comment by DarthSidious666** [comment]
Since glide64 isn't used for this emulator as of later builds it's feasable to close this issue.
