### ISSUE TITLE
Mike Piazza's Strike Zone Crash to Desktop

### ISSUE THREAD

**Issue by Meerkov** [m64p/m64p#237]
**To Reproduce**
1. Load Mike Piazza's Strike Zone
2. It crashes to desktop

Other games work fine.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Dec 29, 2021
 - GPU: 3060

**Additional context**

**Comment by loganmc10** [comment]
I wasn't able to reproduce this, I was able to get in game:

![image](https://user-images.githubusercontent.com/848146/151572269-9edf38a8-550f-4ac3-8587-acf5694e0a64.png)
