### ISSUE TITLE
Linux: "Failed to load core library" crash

### ISSUE THREAD

**Issue by TheGag96** [m64p/m64p#238]
**Describe the bug**
I tried to launch `mupen64plus-gui`, and immediately I get a popup saying "Failed to load core library". Selecting "Core and Video Settings" in the menu immediately segfaults. Trying to load a game yields another "Failed to load core library" and then a segfault.

**To Reproduce**
(See above.)

**Expected behavior**
M64p to not segfault.

**Screenshots**
(N/A)

**Desktop**
 - OS: Linux Mint x64
 - Version: 20.1, Kernel 5.13.0-28
 - GPU: Nvidia GTX 1660 Ti
 - m64p version: Feb 3, 2022 (linux64 download)

**Additional context**

Backtrace on "Core and Video Settings" segfault:

```
#0  0x0000000000000000 in  ()
#1  0x000000000042a5b8 in PluginDialog::PluginDialog(QWidget*) ()
#2  0x000000000041e546 in MainWindow::on_actionPlugin_Settings_triggered() ()
#3  0x0000000000438f59 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#4  0x00000000004392df in MainWindow::qt_metacall(QMetaObject::Call, int, void**) ()
#5  0x00007ffff6de528c in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7a613e6 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff7a63aa2 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff7be9d12 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff7bf14ae in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7bf24d2 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7aaa2b6 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff7bf4adb in QMenu::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff7a67a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7a71343 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6db980a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff7a70457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff7ac6ce4 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff7ac91ec in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff7a67a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7a710f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6db980a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff74387d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#23 0x00007ffff743a10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#24 0x00007ffff741435b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007ffff355132e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#26 0x00007ffff5d4717d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff5d47400 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff5d474a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff6e11435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff6db83ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6dc0116 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x0000000000417bda in main ()
```

**Comment by loganmc10** [comment]
The supported install method on Ubuntu/Minit is snap:
https://snapcraft.io/m64p

You can also try the flatpak on flathub:
https://flathub.org/apps/details/io.github.m64p.m64p

**Comment by TheGag96** [comment]
As I understand, both of those platforms noticeably worsen performance, so I'd rather not use them. I suppose I should just compile myself, then... Though, why keep the Linux raw binaries up at all?

**Comment by loganmc10** [comment]
> As I understand, both of those platforms noticeably worsen performance

No, this is incorrect

The binaries are there because the snap and toolbox images use them

**Comment by TheGag96** [comment]
> No, this is incorrect

I wouldn't be so sure... Here's [the Snap devs](https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm) themselves saying that, and [here's an article](https://www.ctrl.blog/entry/firefox-linux-flatpak-snap.html) saying both of them are slower than native apps. 

I'll just try compiling from source. Thanks for the info.

**Comment by loganmc10** [comment]
The snap article you linked talks about startup performance, which can be slower, although m64p uses the faster compression algorithm mentioned in the article.

For the flatpak article:
> Update (2020-04-14): There’s now an official version of Firefox 75 packaged with Flatpak from Mozilla. It’s published in the Flathub repository. It eliminates the performance problems mentioned in this article, and ships with an MPEG-4/H.264 decoder.

The flatpak they originally tested obviously had something wrong with its codec installation or hardware acceleration support.

Snaps may take a little longer to start, but both systems (snaps and flatpaks) execute code directly on the machine, it's not running in a VM or anything, so the execution/in-game performance will be the same.

**Comment by TheGag96** [comment]
Yes, the article was about startup performance, but I was referring to this general statement they made at the beginning of the article:

> Snaps are self-contained applications, with layered security, and as a result, sometimes, they may have reduced perceived performance compared to those same applications offered via traditional Linux packaging mechanisms.

Which is also backed up by this statement from the other link:

> Flatpak also feels more responsive when scrolling, switching tabs, and other UI operations. Firefox Snap has noticeable lag when performing the same operations.

I'll admit that I do not know how it works, but I guess something about the containerization makes it slower. And sorry, I didn't see that update about Flatpak - good that they fixed that at least.
