### ISSUE TITLE
FYI: Required linux dependency

### ISSUE THREAD

**Issue by Narann** [m64p/m64p#240]
Hi and thanks for your hard work.

I downloaded latest release to test and had do install those dependencies or the app complains about failure to load core:

libsdl2-net-2.0-0
libqt5websockets5

Linux mint.

Maybe it could be written in a readme or detected. IDK.

Feel free to close the ticket.

Keep the good work! :)

**Comment by loganmc10** [comment]
The only supported install methods on Linux are Flatpak and Snap. Anybody else is sort of on their own :) There are so many different distros as well, I haven't bothered doing proper documentation for DIY installs.

**Comment by Narann** [comment]
Make sense!

**Comment by octanervoc** [comment]
Thank you very much for this, @Narann. I do not have enough space left in my drive to install m64p via flatpak and I don't want to mess with Snap either, so I spent quite some time trying to figure out which dependencies were missing. `libqt5websockets5` was very easy to know, as the application refuses to boot without it being installed and the terminal explicitly calls its name, but I had no idea that `libsdl2-net-2.0-0` was another requirement. In fact, I even had `libsdl2-2.0-0` installed, which made me believe I was missing something else entirely.

I'm also on Linux Mint (20.3 Una). If possible, could you tell me how you noticed which libraries were needed for the application to run?

Also, excellent work on m64p, Logan. The final GLideN64 version works perfectly on my setup.

**Comment by loganmc10** [comment]
The ldd application will tell you required dependancies, so for instance:

```ldd mupen64plus-gui``` will tell you which shared libraries are required. You'll have to do that for the other files (like the core library and graphics plugin for instance)

If there is a library missing it will tell you. Each package manager is different, but I know on Fedora doing ```dnf provides missing_library.so``` will tell you which package to install to get that library

**Comment by octanervoc** [comment]
Sorry for the wait. Thank you very much, Logan. I'll keep `ldd` in mind, it'll certainly be useful.

**Comment by constant-current** [comment]
Thanks for this bugreport. Installing those two libs made the latest release running on Debian bullseye.

> `ldd mupen64plus-gui` will tell you which shared libraries are required. You'll have to do that for the other files (like the core library and graphics plugin for instance)
That's the first thing I did on the gui binary (that's why I firstly installed the websocket lib) but wasn't aware of the extra requirement of the mupen lib as the pop-up message "unable to load core" sounded cryptic with no further detail when launched trough the terminal. 
IMHO it should make things clearer if the gui binary includes the core dependencies. After all m64p is an all-included package.
Or at least the error message prompted could be more explicit to avoid those kind of bugreport.

**Comment by loganmc10** [comment]
> IMHO it should make things clearer if the gui binary includes the core dependencies. After all m64p is an all-included package. Or at least the error message prompted could be more explicit to avoid those kind of bugreport.

As mentioned earlier, the only officially supported install methods on Linux are via flatpak or snap, you wouldn't run into these issues if you installed via one of those methods
