### ISSUE TITLE
Trees Clipping into the wall in the OOT intro

### ISSUE THREAD

**Issue by chiefisreal** [m64p/m64p#244]
Trees Clipping into the wall in the OOT intro

**To Reproduce**
1. Start OOT in latest build of m64p and let intro play with the new Graphics plugin that's not GlideN64
2. watch it plays and at the end you will see the trees clipping in and out of the wall around them 

**Expected behavior**
Under GlideN64 this does not happen.

 - OS: Windows
 - Version: Windows 11
 - GPU: GTX 1080

**Additional context**
I know this isn't groundbreaking or top priority.

Have a good one!

**Comment by DarthSidious666** [comment]
Does this still happen with the latest build?

**Comment by chiefisreal** [comment]
Yes

**Comment by DarthSidious666** [comment]
It would be great if a screenshot could be provided too. It helps with seeing how it's affecting the game.

**Comment by DarthSidious666** [comment]
OK I've checked it against this video https://www.youtube.com/watch?v=E-qOhEOL_qw which was recorded on hardware and the trees do this as well. It's not an emulation issue.

**Comment by chiefisreal** [comment]
Yea that vid is what I was talking about 

Project 64 this does not happen that I know for sure, I compared the two. I don't think I have seen it on real hardware playing through the game some 10+ times but that was years ago.

A less accurate emulator is more accurate than real hardware...interesting. Like I Said it's not groundbreaking or that important just something I saw that seemed wrong compared to project 64.

-Chief

**Comment by loganmc10** [comment]
> A less accurate emulator is more accurate than real hardware

I'm not sure I understand this statement. The N64 was not bug-free. In the emulation sense, "accurate" means that it behaves the same as the real hardware. The goal for this emulator is always going to be to emulate the behaviour of the real hardware, not PJ64.
