### ISSUE TITLE
Semicolon in ROM filename causes multiple Open Recent menu entries

### ISSUE THREAD

**Issue by redactedscribe** [m64p/m64p#246]
**Describe the bug**
See issue title.

**To Reproduce**
1. Clear Open Recent menu list.
2. Open a ROM, titled "Game Title; N64; US; 2000.z64" for example.
2. Check Open Recent menu and see the bug manifested (multiple erroneous entries such as "N64", "US", "2000").

**Expected behavior**
Support semicolons in filenames. Create only one recent item for the ROM.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Comment by loganmc10** [comment]
Closed in https://github.com/m64p/m64p/releases/tag/v2022.03.14
