### ISSUE TITLE
Bomberman 64: The Second Attack has a bug that prevents the player from using the analog stick horizontally if played for some minutes

### ISSUE THREAD

**Issue by AkihitoZero5454** [m64p/m64p#247]
I was playing Bomberman 64: The Second Attack and it has a problem (don't know if it also applies to the Japanese version) where if played for some minutes (10-15 or a little longer). It'll prevent the player from using the control stick in horizontal directions.

**Comment by Meerkov** [comment]
10-15 minutes is about how long it takes for me to run into issues on about half of N64 games due to bad cycle counting. I'm guessing this is a cycle count related problem.

**Comment by loganmc10** [comment]
This appears to be a very old issue that affects other emulators:

https://gamefaqs.gamespot.com/n64/257793-bomberman-64-the-second-attack/answers/475591-cant-move-sideways
http://forum.pj64-emu.com/showthread.php?t=2463
http://forum.pj64-emu.com/showthread.php?t=3341

I wonder if it's a bug in the game itself, or maybe a bug in the ROM dump. I guess it could be an emulator issue, but I've never heard of a problem like this before, where controller input is affected in certain directions

**Comment by HappehLemons** [comment]
I’ve had this bug as well, and it’s been reported recently on the Mupen64-Next build on Retroarch. 

It happens in Project 64 as well. Game has always been impossible to beat on an emulator because of this.

Been seeing this bug pop up forever at this point, it’s one of the few N64 games that can’t be emulated. Best “anti cheat” ever, lol.

**Comment by BParks21** [comment]
This happens with every n64 emulator I've tested.  Mupen64-Next, project64 and this one.

**Comment by DarthSidious666** [comment]
I've not come across this bug and I've played through at least one level.
Can you confirm it still happens?

**Comment by DarthSidious666** [comment]
OK I've played this for a good hour and the bug refuses to appear, so I'm marking this as solved.

**Comment by BParks21** [comment]
Some sessions you can play for hours and it won't happen. It's a really strange issue.
