### ISSUE TITLE
Opening Sin and Punishment rom crashes m64p.

### ISSUE THREAD

**Issue by DevTime217** [m64p/m64p#249]
**Describe the bug**
When I open Sin and Punishment on m64p, the emulator crashes and I don't know how to fix it.

**To Reproduce**
1. Open a downloaded Sin and Punishment rom in m64p

**Expected behavior**
I expected the emulator to open Sin and Punishment, since it does so on Project64

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - GPU: RTX 3070

**Screenshots**
![Screenshot 2022-04-02 144044](https://user-images.githubusercontent.com/73371028/161396927-4aa0d48e-9071-44d3-b189-86cb4f2fdfbc.png)

**Comment by loganmc10** [comment]
Please do not post links to ROMs

**Comment by DevTime217** [comment]
My apologies. I wasn't aware.

**Comment by DevTime217** [comment]
Were you able to replicate my issue and find a fix for it?

**Comment by elektronicznypank** [comment]
Do you have english patched version? This version crashed my m64p as well.

There are two english patched versions of this game. Second one is known to work.
