### ISSUE TITLE
Gameplay stutter on all games past Windows April 3 build: m64p-win64-67dfe5c

### ISSUE THREAD

**Issue by cole-seph** [m64p/m64p#250]
**Describe the bug**
After getting prompted to install an m64p update, I updated to the April 5 release and noticed that all loaded ROMS seemed to have issues with stuttering that made games unplayable. For some games, it takes a minute to notice this, which usually seems to be when the game goes from story mode to actual input/action mode.
Example: GoldenEye menu loads fine but once the level begins, you can hear the music is stuttering and then will notice gameplay is stuttering

Earlier Windows builds: m64p-win64-33c43f5, m64p-win64-c7ca130 confirmed to not have this problem for me

**To Reproduce**
Load any ROM using similar Windows specs on builds "m64p-win64-67dfe5c" and later

**Expected behavior**
Games should not freeze / stutter

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 version 20H2
Processor: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, 3200 Mhz, 4 Core(s), 4 Logical Processor(s)
GPU: Radeon RX 560 Series
Memory: 8 GM RAM

**Additional context**

**Comment by loganmc10** [comment]
Do you have upscaling enabled in the video settings?

**Comment by cole-seph** [comment]
It _was_ set to "2", yes. I have since turned it off (set back to "0") but this doesn't seem to resolve anything

**Comment by danielah05** [comment]
i am starting to get this exact problem as well, have not touched any of my settings and games like super mario 64 that ran completely fine before are now a laggy mess

**Comment by thekovic** [comment]
For the record, I cannot replicate any issues on my Windows machine. I tried playing GoldenEye and Super Mario 64 and they both ran like butter

**Comment by cole-seph-fi** [comment]
MarioKart doesn’t seem to suffer from these issues for me but I can still replicate on Goldeneye and Sarges Heroes

**Comment by cole-seph** [comment]
MarioKart doesn’t seem to suffer from these issues for me but I can still replicate on Goldeneye and Sarges Heroes

**Comment by ForeskinJohn** [comment]
this happens to me, but only when I upscale passed 4x, anything under 8x runs perfectly.

**Comment by KuroRaiden** [comment]
I'm having the same issue.
I updated it to the April 5 version a few days ago and been having issue since. 

-Hardware-
GPU
Radeon RX 580 Series
Primary/Discrete
CPU
AMD Ryzen 5 2600 Six-Core Processor
6 Cores
VRAM
4096 MB
GDDR5 1850 MHz
RAM
32 GB

**Comment by Jj0YzL5nvJ** [comment]
Undefined behaviour by missing dynarec?
What if y'all reset `R4300Emulator` = `1`?

**Comment by KuroRaiden** [comment]
I did that. Reset everything to default and it still stuttered on the April
build so i rolled back to the March 31 build and it had minor issues in
start up but worked perfectly fine after a restart once the rom booted
after it first try. Can even play on 4x on the games i was playing before.

**Comment by Jj0YzL5nvJ** [comment]
**Re-set** `R4300Emulator` to `1`... only that.

**Comment by ForeskinJohn** [comment]
Body Harvest also stutters terribly, im not sure if this is at all related to the issue mentioned above, this is also a pretty difficult game to emulate properly ive heard

**Comment by cole-seph** [comment]
> Re-set R4300Emulator to 1... only that.
Also did not fix for me but thank you. 

@danielah05 can you list your hardware resources into this issue?
I'm assuming this is hardware specific if only certain users are affected and it would be good to try and look for any hardware consistencies here for the devs.

**Comment by danielah05** [comment]
> > Re-set R4300Emulator to 1... only that.
> > Also did not fix for me but thank you.
> 
> @danielah05 can you list your hardware resources into this issue? I'm assuming this is hardware specific if only certain users are affected and it would be good to try and look for any hardware consistencies here for the devs.

yeah sorry my bad

Windows 10 Pro 21H1
Processor: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz   3.50 GHz
GPU: NVIDIA GeForce GTX 970
Memory: 32 GB RAM

**Comment by cole-seph** [comment]
After seeing this bug seemed to also apply to older builds I was reverting to, it seems like the issue has something to do with settings stored in `mupen64plus.cfg` file in your Roaming profile settings.

@danielah05 , @ForeskinJohn if you're still having this issue, the workaround for me is: 
- Go back to the releases page and find the release you had before updating to whatever broken version you ended up with
- Go into C:\users\(your_username)\AppData\Roaming\Mupen64Plus and backup your `saves` and any configuration `.ini` files. Exclude the `mupen64plus.cfg` file. 
- Rename your `Mupen64Plus` folder to something like `Mupen64Plus.bak` to back it up
- Launch the reverted version of mupen64plus you just downloaded
- This will create a new blank preferences folder in your `AppData\Roaming` folder, which seems to fix the problem
- Copy your backed up `saves` and `.ini` controller config files into this directory and replace the pre-existing files
- Re-launch mupen64plus
- Re-configure any reset settings like upscaling or whatever else
- Re-launch your Roms and confirm everything working

Then you should at least be up and running again.

**Comment by danielah05** [comment]
> After seeing this bug seemed to also apply to older builds I was reverting to, it seems like the issue has something to do with settings stored in `mupen64plus.cfg` file in your Roaming profile settings.
> 
> @danielah05 , @ForeskinJohn if you're still having this issue, the workaround for me is:
> 
>     * Go back to the releases page and find the release you had before updating to whatever broken version you ended up with (for me, I had to go back to the Dec. 29, 2021 build)
> 
>     * Go into C:\users(your_username)\AppData\Roaming\Mupen64Plus and backup your `saves` and any configuration `.ini` files. Exclude the `mupen64plus.cfg` file.
> 
>     * Rename your `Mupen64Plus` folder to something like `Mupen64Plus.bak` to back it up
> 
>     * Launch the reverted version of mupen64plus you just downloaded
> 
>     * This will create a new blank preferences folder in your `AppData\Roaming` folder, which seems to fix the problem
> 
>     * Copy your backed up `saves` and `.ini` controller config files into this directory and replace the pre-existing files
> 
>     * Re-launch mupen64plus
> 
>     * Re-configure any reset settings like upscaling or whatever else
> 
>     * Re-launch your Roms and confirm everything working
> 
> 
> Then you should at least be up and running again.

yeah that fixes the lag in said older version (which is still nice), sadly doesnt fix the problem in the latest versions.
thanks anyways!

**Comment by Kugelblitz360** [comment]
I can confirm that current Windows builds have stuttering on basically all games and I think it starts as soon as audio kicks in. As there are NO audio config options this might be a buffering issue (wild guess)? Running Rogue Squadron with 2x scaling uses less then 10% CPU on my machine and less then 20% GPU (Nvidia), so there schould be enough breathing room. Stuttering even happens when basically no polys are pushed, so audio buffering is not the worst guess. It's not screen refresh, even when I locked my screen to 60Hz identical stuttering happens.

**Comment by loganmc10** [comment]
Closing this as a dulplicate of https://github.com/m64p/m64p/issues/223

**Comment by cole-seph** [comment]
I’m not sure if a fix was implemented in the latest release, but unfortunately the latest release seems to still yield the same problem for me.
