### ISSUE TITLE
Screen is completely garbled when loading game

### ISSUE THREAD

**Issue by mariosmentor** [m64p/m64p#253]
**Describe the bug**
Shortly after I installed the Small Wayland fix update, I played a romhack of Quest 64 (aptly named Hard Mode) for a short while. No issues arose, outside of audio lag when playing in fullscreen. (this was nonexistent when playing in windowed mode) I saved my progress after about an hour of play, and closed the emulator. The next day, regardless of what game I loaded, the screen would show a garbled mess of pixels, with audio and gameplay still intact. I tried fiddling with settings, and reverting to default settings. I don't know what could've happened.

**Screenshots**
![m64p garbled](https://user-images.githubusercontent.com/71528967/173289974-6c73eedf-d686-4a5e-8bea-f2ecf133d22d.png)

**Desktop:**
 - OS: Windows
 - Version: 10
 - GPU: NVIDIA GeForce GTX 1060 3GB
 - Processor: Intel Core i5-7400

**Comment by psymage** [comment]
I am also having a similar issue on Linux with the Flatpak on the latest version:

![m64p garbled graphics](https://user-images.githubusercontent.com/87615056/174451589-532f5094-7800-4333-b844-8b0a0bce3c42.png)

**Comment by loganmc10** [comment]
I think this should be fixed now, please reopen if it's still a problem
