### ISSUE TITLE
Auto Updater freezes

### ISSUE THREAD

**Issue by zant0** [m64p/m64p#261]
The auto updater doesn't work since v2022.07.1 and in all later versions.
You start the emulator and it asks you if you want to update. Click "Yes". 
It runs through the usual steps but stops at "Moving files into place".
The emulator freezes here and never finishes.

You can close the updater and then a new instance of the emulator gets opened but the old one is still there and has to be closed via task manager.

OS: Windows 10 64bit

**Comment by loganmc10** [comment]
Thanks I did notice this the other day, I just released a fix - https://github.com/m64p/m64p/releases/tag/v2022.07.5

Unfortunately you'll need to manually update to that version before auto-updating starts working again for future releases
