### ISSUE TITLE
bilinear filtering is no use

### ISSUE THREAD

**Issue by shinslash** [m64p/m64p#262]
After v2022.07.3 I can't see any difference bilinear filtering on or off.
v2022.07.3 said "Fix bilinear filtering setting". Actually it broke bilinear filtering.
bilinear filtering works well in v2022.07.2

**Comment by loganmc10** [comment]
Please attach screenshots to show what you mean

**Comment by shinslash** [comment]
![捕获](https://user-images.githubusercontent.com/76992608/178152136-ca244c2d-6164-4049-8303-9a79674ab2de.JPG)
![捕获1](https://user-images.githubusercontent.com/76992608/178152140-5c87fc36-f58e-425b-a800-c6bdf67cc99e.JPG)
![捕获2](https://user-images.githubusercontent.com/76992608/178152275-2e203ec0-e122-4488-b755-4586bf91616e.JPG)

**Comment by loganmc10** [comment]
The problem before v2022.07.3 is that Vulkan was applying its own filtering on top of the filtering done by Parallel-RDP

With filtering enabled on latest version:
![1080_snowboarding-000](https://user-images.githubusercontent.com/848146/178158314-300c14ab-ed09-48c4-825a-5b32570827b6.png)

With filtering disabled on latest version:
![1080_snowboarding-001](https://user-images.githubusercontent.com/848146/178158323-323f911c-a71d-46b1-b22b-b7cc8e25c060.png)

The difference is subtle but it is there, and the effect is working as intended. If you'd like further post-processing I'd suggest a program like ReShade
