### ISSUE TITLE
Emulator freezes on loading a save state

### ISSUE THREAD

**Issue by thekovic** [m64p/m64p#263]
**Describe the bug**
When I saw the new release, I was excited to begin testing the new lag emulation (particularly in DOOM 64 and its lag clips that are used in speedrunning) but during testing I found out that I couldn't load any save states that I made. Using the GUI in windowed mode caused the emulator to show the first frame of the save state but then freeze. Using the hotkeys, the emulator outright crashes out of the game.

**To Reproduce**
1. Launch any game (personally replicated in DOOM 64 and Indiana Jones)
2. Make a save state
3. Attempt to load that save state

**Expected behavior**
Save states working

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: GTX 1050Ti

Here are two save states that I made today.
[save.zip](https://github.com/m64p/m64p/files/9132417/save.zip)

**Comment by loganmc10** [comment]
I don't think loading save states from older builds is going to work, the emulation code has changed too much. But you should be able to save and load from this version

**Comment by loganmc10** [comment]
Save states created with previous builds, or save states made with that build?

**Comment by thekovic** [comment]
New save states, created with the new build

**Comment by thekovic** [comment]
New save states, created with the new build

**Comment by despoa** [comment]
I can confirm thekovic's new issue. I created a new save state in Super Mario 64 and it crashes when trying to load it.

**Comment by loganmc10** [comment]
Should be fixed in https://github.com/m64p/m64p/releases/tag/v2022.07.8, please let me know
