### ISSUE TITLE
Video Screen size bug HiDPI

### ISSUE THREAD

**Issue by jeltaqq** [m64p/m64p#268]
**Describe the bug**

**To Reproduce**
1. Go to Core and Video settings > 'PallaLLEI Video'
2. Check to 'ScreenWidth/height'
3. Go to 'File > Open ROM'
4. Load on any ROMs
5. Go to 'File > Open ROM' again
6. Load on any ROMs
7. Check to ScreenWidth/height
8. See error

**Expected behavior**
Keep the previous ScreenWidth/height.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Geforce 750Ti

**Additional context**
None

**Comment by loganmc10** [comment]
I'm sorry, I don't know if I fully understand, are you saying that the width and height are not properly scaled on a high DPI screen?

**Comment by jeltaqq** [comment]
I'm sorry, The width and height are increased on a high DPI screen. Each time you stop any Game.

**Comment by jeltaqq** [comment]
I don't like the numbers that it puts in for width and height recorded in the Video-Parallel section of mupen64plus.cfg.

```
[Video-Parallel]
# Screen width 
ScreenWidth = 800
# Screen height
ScreenHeight = 600
```

When I close a ROM, m64p multiply the width and height values by the pixel ratio. I consider this a bug. Next time, the increased width and height values will be used, so window is wrong size.

**Comment by loganmc10** [comment]
Should be fixed in https://github.com/m64p/m64p/releases/tag/v2022.07.8, please let me know

**Comment by jeltaqq** [comment]
It seems to work fine. Thank you.
