### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by MorbiousMan** [m64p/m64p#277]
I Can't Launch Any ROM Of N64 It Gives Me This Error:Could not start GFX plugin
![ot-63-29-07-22](https://user-images.githubusercontent.com/110247549/181792194-8d21f9e5-de0a-4c82-b0b8-cc62c87b615a.png)

**Comment by loganmc10** [comment]
This means your computer doesn't support Vulkan 1.1, you can try updating your graphics drivers

**Comment by elektronicznypank** [comment]
What gpu do you have?
