### ISSUE TITLE
performance issues in the last release

### ISSUE THREAD

**Issue by Petersilientroll** [m64p/m64p#278]
I have massive performance issues in 8.1 compared to 7.12 (in GT 64, Destruction Derby 64 etc.) on my system (Windows 10 x64, i7-4790 (Haswell), RTX 2060S (Turing), 16 GByte DDR3-RAM). FPS goes down to 40 and sound stutters. :'(

**Comment by loganmc10** [comment]
Sorry, I can't consider this a bug unless there is a specific suggestion somewhere to improve performance. The increased focus on accuracy lately has increased the CPU requirements of the emulator.

This isn't to say that there aren't improvements that could be made somewhere, but this report doesn't get us closer to a solution.
