### ISSUE TITLE
Mario Kart 64 seems very slow after the timing accuracy releases

### ISSUE THREAD

**Issue by dezraj** [m64p/m64p#280]
**Describe the bug**
The game seems to have been affected by many slowdowns after the timing accuracy changes were implemented in m64p.

**To Reproduce**
If you play on Toad's Turnpike track in the Flower Cup you should notice many slowdowns. It will take much more time to finish it. Hitting a bus or a car also triggers the slowdown effect especially if there are other vehicles around.

**Expected behavior**
It wasn't supposed to run like that and it didn't before v2022.07.7. I have the game in the original hardware and this doesn't happen there.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1809
 - GPU: GTX 1660 Ti

**Additional context**
The audio plays fine and the window status bar shows 60 fps constantly.

Anyway, I think you should already be aware of this issue, but I decided to file a bug report in case someone else also experiences that and comes here for help. Thank you for your time and work.

**Comment by loganmc10** [comment]
Thanks for this report. This should hopefully be fixed in the latest release, please let me know

**Comment by dezraj** [comment]
Hello! I've just tried it here and I can no longer feel the slowdowns as far as I can tell. Thank you so much for your fast work on this.

By the way, this is not related to this issue, but I'm seeing some weird color effects in this game. The track looks like a smudgy painting and the sky shows clearly a difference in the color gradation. Take a look here:
https://imgur.com/a/evPYTaw

I don't know the technical term exactly, perhaps "color banding"? This expected for the ParaLLEI plugin, right? I've noticed it becomes less noticeable if you run the game at native internal resolution, but then the visual quality is really poor...

Finally, about the 60 fps information in the status bar, isn't it supposed to be showing 30 fps for this game?

Anyway, I'm sorry for taking your time with those questions.

Thank you again for your work.

**Comment by loganmc10** [comment]
Mario Kart employed a lot of 2D images even though it's a "3D" game, so yes I assume some of it won't look great when upscaled.

As for the FPS, that counter is showing the NTSC/PAL refresh rate. Even if a game only updated the image at 20/30FPS, the screen itself would always refresh 50/60 times a second, depending on the region. It's mostly so you can tell if your computer is running the game at full speed or not
